
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.com.curdboard.projectboard: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: inseon
    password: wmf8956
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:h2:mem:testdb
#    username: sa
#    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.default_batch_fetch_size: 100
  sql.init.mode: always

#  ---
#
#  spring:
#    config.active.on-profile: testdb
#    datasource:
#      url: jdbc:h2:mem:board;mode=sql
#      driverClassName : org.h2.Driver
#    sql.init.mode : always
#    test.database.replace: none
